DROP Table UserAuthInfo CASCADE CONSTRAINTS
/*PURGE*/;
DROP Table User CASCADE CONSTRAINTS
/*PURGE*/;
DROP Table PointsSystem CASCADE CONSTRAINTS
/*PURGE*/;
DROP Table GameRoster CASCADE CONSTRAINTS
/*PURGE*/;
DROP Table Character CASCADE CONSTRAINTS
/*PURGE*/;

